# Generated by Django 3.1.1 on 2025-12-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20251217_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('max_participants', models.IntegerField(default=0, help_text='0表示不限制', verbose_name='最大参与人数')),
                ('status', models.SmallIntegerField(choices=[(0, '待审批'), (1, '已通过'), (2, '已拒绝')], default=0, verbose_name='审批状态')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='管理员回复')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staff', verbose_name='发起教师')),
            ],
            options={
                'verbose_name': '校园活动',
                'verbose_name_plural': '校园活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.activity', verbose_name='活动')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'ordering': ['-registered_at'],
                'unique_together': {('activity', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ActivityFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.activity', verbose_name='活动')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '活动评价',
                'verbose_name_plural': '活动评价',
                'ordering': ['-created_at'],
                'unique_together': {('activity', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ActivityAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='是否出席')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.activity', verbose_name='活动')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staff', verbose_name='签到确认人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '活动签到',
                'verbose_name_plural': '活动签到',
                'ordering': ['-checked_at'],
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
